[Variables]

;-----------------------
; LAYOUT

Stylesheet=Enigma Dark

;-----------------------
; GENERAL

Note1Path=[#@]User\Notes\Notes.txt
Note2Path=[#@]User\Notes\Tasks.txt
Note3Path=[#@]User\Notes\About.txt
NoteHeight=200
Drive1=C
Drive2=E
Drive3=F
NetworkMaxDownload=1000000
NetworkMaxUpload=500000
SystemGraphType=Floating
CalendarEventFile=[#@]User\Calendars\Holidays.xml
CalendarShowEvents=1
CalendarExtraDays=1
CalendarLeadingZeroes=0
CalendarMondays=0
GalleryPath=%USERPROFILE%\Pictures
GallerySubfolders=1
GalleryPosition=Center
GalleryRatio=3/4
VolumeIncrement=5
TriptychInterval=30
TriptychDisabled=0
ProcessInterval=5

;-----------------------
; MUSIC

MusicPlayerType=1
MusicPlayer=AIMP

;-----------------------
; FEEDS

Feed1=http://news.google.com/news?pz=1&ned=us&hl=en&topic=h&num=10&output=rss
Feed2=http://rainmeter.net/forum/feed.php
Feed3=http://kaelri.com/feed/
GmailUsername=YourUsername
GmailPassword=YourPasswordHere
GmailDomain=domain.com
GmailUrl=https://[#GmailUsername]:[#GmailPassword]@gmail.google.com/gmail/feed/atom
FacebookFeed=YourFacebookFeedHere
GoogleCalendar1=YourCalendarAddressHere
GoogleCalendar2=YourCalendarAddressHere
GoogleCalendar3=YourCalendarAddressHere
GoogleCalendarWriteEvents=1
RTMusername=YourUserNameHere
RTMpassword=YourPasswordHere
RTMlist1=YourListNumberHere
RTMlist2=YourListNumberHere
RTMlist3=YourListNumberHere
TwitterUsername=YourUsernameHere
TwitterPassword=YourPasswordHere

;-----------------------
; WORLD

WeatherCode=
WeatherCodeName=
WeatherCodeLat=
WeatherCodeLon=
Unit=f
World1WeatherCode=44418
World1WeatherCodeName=London
World1WeatherCodeLat=51.51
World1WeatherCodeLon=-0.13
World2WeatherCode=2514815
World2WeatherCodeName=Washington
World2WeatherCodeLat=38.9
World2WeatherCodeLon=-77.03
World3WeatherCode=455825
World3WeatherCodeName=Rio de Janeiro
World3WeatherCodeLat=-22.98
World3WeatherCodeLon=-43.2

;-----------------------
; APPS

App1=Chrome
App1Path=chrome.exe
App1PathHandle=chrome.exe
App1Label=WEB
App1Icon=[#@]Images\Launcher\Chrome.[#ColorImage].png
App2=VSCode
App2Path=H:\Users\farha\AppData\Local\Programs\Microsoft VS Code\Code.exe
App2PathHandle=Code.exe
App2Label=CODE
App2Icon=C:\Users\farha\Downloads\Rainmeter_Utils\Icons\vscode-dark.png
App3=Explorer
App3Path=explorer.exe
App3PathHandle=explorer.exe
App3Label=FILES
App3Icon=[#@]Images\Launcher\Start.[#ColorImage].png
App4=WhatsApp
App4Path=C:\Users\farha\AppData\Local\WhatsAppWhatsApp.exe
App4PathHandle=WhatsAppWhatsApp.exe
App4Label=CHAT
App4Icon=C:\Users\farha\Downloads\Rainmeter_Utils\Icons\whatsapp.png
App5=Discord
App5Path=C:\Users\farha\AppData\Local\Discord\Update.exe
App5Handle=rainmeter.exe
App5Label=CHAT
App5Icon=C:\Users\farha\Downloads\Rainmeter_Utils\Icons\discord.png

;-----------------------
; SEARCH

Search1=Google
Search1Command="http://google.com/search?q=$UserInput$"
Search1Icon=[#@]Images\Search\Google.[#ColorImage].png
Search2=Wikipedia
Search2Command="http://en.wikipedia.org/wiki/$UserInput$"
Search2Icon=[#@]Images\Search\Wiki.[#ColorImage].png
Search3=YouTube
Search3Command="http://www.youtube.com/results?search_query=$UserInput$"
Search3Icon=[#@]Images\Search\YouTube.[#ColorImage].png
Search4=Twitter
Search4Command="https://twitter.com/#!/search/$UserInput$"
Search4Icon=[#@]Images\Search\Twitter.[#ColorImage].png
Search5=Rainmeter.net
Search5Command="https://www.google.com/search?q=site%3Ahttp%3A%2F%2Frainmeter.net%2Fcms%2F%20$UserInput$"
Search5Icon=[#@]Images\Search\Run.[#ColorImage].png
TaskbarHideTriptych=0
App5PathHandle=Update.exe
