[Variables]

;Large Launcher Buttons====================

LLT=Chrome
;Program Name
LLP=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
;Program Path
LLI=#SKINSPATH#\avengers\Large Launchers\chrome.png
;Program Icon

LLT2=Control Panel
LLP2=C:\Users\yash\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\System Tools\Control Panel
LLI2=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Large Launchers\Control Panel.png

LLT3=Steam
LLP3=C:\Users\yash\Documents\meditation
LLI3=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Large Launchers\Steam.png

LLT4=Mozila Firefox
LLP4=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
LLI4=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Large Launchers\iTunes.png

LLT5=uTorrent
LLP5=C:\Users\yash\AppData\Roaming\uTorrent\uTorrent.exe
LLI5=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Large Launchers\uTorrent.png

LLT6=Skype
LLP6=C:\Program Files (x86)\Skype\phone\skype.exe
LLI6=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Large Launchers\Skype.png

;Small Launcher Buttons===========================

SLT1=TF2
SLP1=C:\Users\yash\Desktop\adt-bundle-windows-x86_64-20140624\SDK Manager.exe
SLI1=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Small Launchers\game.ico

SLT2=BROFORCE
SLP2=C:\Program Files (x86)\Photon Plus\Huawei\Photon Plus.exe
SLI2=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Small Launchers\BROFORCE.png

SLT3=Coll Editor
SLP3=C:\Users\yash\Documents\Coll Editor\CollEditor.exe
SLI3=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Small Launchers\database-icon.png

SLT4=Tool Kit
SLP4=C:\Samsung Galaxy Note2 ToolKit\ToolKit.exe
SLI4=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Small Launchers\407885d1261684528-slider-carrier-icon-requests-post-them-here-batman1.png

SLT5=Paradise City
SLP5=C:\Program Files (x86)\Electronic Arts\Burnout(TM) Paradise The Ultimate Box\BurnoutParadise.exe
SLI5=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Small Launchers\Premiere.png

SLT6=Recycle Bin
SLP6=::{645ff040-5081-101b-9f08-00aa002f954e}
SLI6=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Small Launchers\database-icon.png

;Folder Launcher BUttons=========================

FLP1=%UserProfile%\Downloads
;Folder Path
FLN1=Downloads
;Folder Name

FLP2=%UserProfile%\Dropbox
FLN2=Dropbox

FLP3=%UserProfile%\Music
FLN3=Music

FLP4=#SKINSPATH#
FLN4=Rainmeter

FLP5=%UserProfile%\Videos
FLN5=Videos

FLP6=%UserProfile%\Pictures
FLN6=Pictures

FLP7=%UserProfile%\Documents
FLN7=Documents

;Clock Webpages==============================

WN=Facebook
;Webpage Name
WA=https:\\Facebook.com
;Webpage Address

WN2=Twitter
WA2=http:\\wwwtwitter.com

WN3=Sammobile
WA3=http:\\www.sammobile.com

WN4=Deviantart
WA4=http:\\deviantart.com

WN5=XDA Forums
WA5=http://forum.xda-developers.com/

WN6=Yahoo Mail
WA6=http:\\mail.yahoo.com

;Misc======================

player=CAD
Drive=C:

LLT1=Chrome
LLP1=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
LLI1=C:\Users\yash1\OneDrive\Documents\Rainmeter\Skins\Avengers\Large Launchers\Chrome.png
WA1=http:\\www.facebook.com
