[MeasureBandSmooth0]
Measure=Calc
Formula=(MeasureBand0+MeasureBand0+MeasureBand1)/3+(1/200)
AverageSize=5

[MeasureBandSmooth1]
Measure=Calc
Formula=(MeasureBand0+MeasureBand1+MeasureBand2)/3+(1/200)
AverageSize=5

[MeasureBandSmooth2]
Measure=Calc
Formula=(MeasureBand1+MeasureBand2+MeasureBand3)/3+(1/200)
AverageSize=5

[MeasureBandSmooth3]
Measure=Calc
Formula=(MeasureBand2+MeasureBand3+MeasureBand4)/3+(1/200)
AverageSize=5

[MeasureBandSmooth4]
Measure=Calc
Formula=(MeasureBand3+MeasureBand4+MeasureBand5)/3+(1/200)
AverageSize=5

[MeasureBandSmooth5]
Measure=Calc
Formula=(MeasureBand4+MeasureBand5+MeasureBand6)/3+(1/200)
AverageSize=5

[MeasureBandSmooth6]
Measure=Calc
Formula=(MeasureBand5+MeasureBand6+MeasureBand7)/3+(1/200)
AverageSize=5

[MeasureBandSmooth7]
Measure=Calc
Formula=(MeasureBand6+MeasureBand7+MeasureBand8)/3+(1/200)
AverageSize=5

[MeasureBandSmooth8]
Measure=Calc
Formula=(MeasureBand7+MeasureBand8+MeasureBand9)/3+(1/200)
AverageSize=5

[MeasureBandSmooth9]
Measure=Calc
Formula=(MeasureBand8+MeasureBand9+MeasureBand10)/3+(1/200)
AverageSize=5

[MeasureBandSmooth10]
Measure=Calc
Formula=(MeasureBand9+MeasureBand10+MeasureBand11)/3+(1/200)
AverageSize=5

[MeasureBandSmooth11]
Measure=Calc
Formula=(MeasureBand10+MeasureBand11+MeasureBand12)/3+(1/200)
AverageSize=5

[MeasureBandSmooth12]
Measure=Calc
Formula=(MeasureBand11+MeasureBand12+MeasureBand13)/3+(1/200)
AverageSize=5

[MeasureBandSmooth13]
Measure=Calc
Formula=(MeasureBand12+MeasureBand13+MeasureBand14)/3+(1/200)
AverageSize=5

[MeasureBandSmooth14]
Measure=Calc
Formula=(MeasureBand13+MeasureBand14+MeasureBand15)/3+(1/200)
AverageSize=5

[MeasureBandSmooth15]
Measure=Calc
Formula=(MeasureBand14+MeasureBand15+MeasureBand16)/3+(1/200)
AverageSize=5

[MeasureBandSmooth16]
Measure=Calc
Formula=(MeasureBand15+MeasureBand16+MeasureBand17)/3+(1/200)
AverageSize=5

[MeasureBandSmooth17]
Measure=Calc
Formula=(MeasureBand16+MeasureBand17+MeasureBand18)/3+(1/200)
AverageSize=5

[MeasureBandSmooth18]
Measure=Calc
Formula=(MeasureBand17+MeasureBand18+MeasureBand19)/3+(1/200)
AverageSize=5

[MeasureBandSmooth19]
Measure=Calc
Formula=(MeasureBand18+MeasureBand19+MeasureBand20)/3+(1/200)
AverageSize=5

[MeasureBandSmooth20]
Measure=Calc
Formula=(MeasureBand19+MeasureBand20+MeasureBand21)/3+(1/200)
AverageSize=5

[MeasureBandSmooth21]
Measure=Calc
Formula=(MeasureBand20+MeasureBand21+MeasureBand22)/3+(1/200)
AverageSize=5

[MeasureBandSmooth22]
Measure=Calc
Formula=(MeasureBand21+MeasureBand22+MeasureBand23)/3+(1/200)
AverageSize=5

[MeasureBandSmooth23]
Measure=Calc
Formula=(MeasureBand22+MeasureBand23+MeasureBand24)/3+(1/200)
AverageSize=5

[MeasureBandSmooth24]
Measure=Calc
Formula=(MeasureBand23+MeasureBand24+MeasureBand25)/3+(1/200)
AverageSize=5

[MeasureBandSmooth25]
Measure=Calc
Formula=(MeasureBand24+MeasureBand25+MeasureBand26)/3+(1/200)
AverageSize=5

[MeasureBandSmooth26]
Measure=Calc
Formula=(MeasureBand25+MeasureBand26+MeasureBand27)/3+(1/200)
AverageSize=5

[MeasureBandSmooth27]
Measure=Calc
Formula=(MeasureBand26+MeasureBand27+MeasureBand28)/3+(1/200)
AverageSize=5

[MeasureBandSmooth28]
Measure=Calc
Formula=(MeasureBand27+MeasureBand28+MeasureBand29)/3+(1/200)
AverageSize=5

[MeasureBandSmooth29]
Measure=Calc
Formula=(MeasureBand28+MeasureBand29+MeasureBand30)/3+(1/200)
AverageSize=5

[MeasureBandSmooth30]
Measure=Calc
Formula=(MeasureBand29+MeasureBand30+MeasureBand31)/3+(1/200)
AverageSize=5

[MeasureBandSmooth31]
Measure=Calc
Formula=(MeasureBand30+MeasureBand31+MeasureBand32)/3+(1/200)
AverageSize=5

[MeasureBandSmooth32]
Measure=Calc
Formula=(MeasureBand31+MeasureBand32+MeasureBand33)/3+(1/200)
AverageSize=5

[MeasureBandSmooth33]
Measure=Calc
Formula=(MeasureBand32+MeasureBand33+MeasureBand34)/3+(1/200)
AverageSize=5

[MeasureBandSmooth34]
Measure=Calc
Formula=(MeasureBand33+MeasureBand34+MeasureBand35)/3+(1/200)
AverageSize=5

[MeasureBandSmooth35]
Measure=Calc
Formula=(MeasureBand34+MeasureBand35+MeasureBand36)/3+(1/200)
AverageSize=5

[MeasureBandSmooth36]
Measure=Calc
Formula=(MeasureBand35+MeasureBand36+MeasureBand37)/3+(1/200)
AverageSize=5

[MeasureBandSmooth37]
Measure=Calc
Formula=(MeasureBand36+MeasureBand37+MeasureBand38)/3+(1/200)
AverageSize=5

[MeasureBandSmooth38]
Measure=Calc
Formula=(MeasureBand37+MeasureBand38+MeasureBand39)/3+(1/200)
AverageSize=5

[MeasureBandSmooth39]
Measure=Calc
Formula=(MeasureBand38+MeasureBand39+MeasureBand40)/3+(1/200)
AverageSize=5

[MeasureBandSmooth40]
Measure=Calc
Formula=(MeasureBand39+MeasureBand40+MeasureBand41)/3+(1/200)
AverageSize=5

[MeasureBandSmooth41]
Measure=Calc
Formula=(MeasureBand40+MeasureBand41+MeasureBand42)/3+(1/200)
AverageSize=5

[MeasureBandSmooth42]
Measure=Calc
Formula=(MeasureBand41+MeasureBand42+MeasureBand43)/3+(1/200)
AverageSize=5

[MeasureBandSmooth43]
Measure=Calc
Formula=(MeasureBand42+MeasureBand43+MeasureBand44)/3+(1/200)
AverageSize=5

[MeasureBandSmooth44]
Measure=Calc
Formula=(MeasureBand43+MeasureBand44+MeasureBand45)/3+(1/200)
AverageSize=5

[MeasureBandSmooth45]
Measure=Calc
Formula=(MeasureBand44+MeasureBand45+MeasureBand46)/3+(1/200)
AverageSize=5

[MeasureBandSmooth46]
Measure=Calc
Formula=(MeasureBand45+MeasureBand46+MeasureBand47)/3+(1/200)
AverageSize=5

[MeasureBandSmooth47]
Measure=Calc
Formula=(MeasureBand46+MeasureBand47+MeasureBand48)/3+(1/200)
AverageSize=5

[MeasureBandSmooth48]
Measure=Calc
Formula=(MeasureBand47+MeasureBand48+MeasureBand49)/3+(1/200)
AverageSize=5

[MeasureBandSmooth49]
Measure=Calc
Formula=(MeasureBand48+MeasureBand49+MeasureBand49)/3+(1/200)
AverageSize=5
