[MeterBar0]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth0]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar1]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth1]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar2]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth2]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar3]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth3]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar4]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth4]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar5]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth5]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar6]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth6]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar7]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth7]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar8]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth8]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar9]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth9]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar10]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth10]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar11]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth11]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar12]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth12]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar13]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth13]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar14]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth14]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar15]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth15]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar16]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth16]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar17]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth17]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar18]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth18]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar19]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth19]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar20]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth20]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar21]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth21]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar22]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth22]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar23]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth23]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar24]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth24]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar25]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth25]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar26]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth26]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar27]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth27]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar28]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth28]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar29]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth29]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar30]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth30]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar31]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth31]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar32]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth32]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar33]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth33]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar34]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth34]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar35]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth35]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar36]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth36]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar37]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth37]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar38]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth38]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar39]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth39]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar40]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth40]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar41]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth41]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar42]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth42]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar43]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth43]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar44]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth44]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar45]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth45]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar46]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth46]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar47]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth47]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar48]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth48]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1

[MeterBar49]
Meter=Shape
X=10R
Y=200
Shape=Rectangle 0,0,20,(-200*[MeasureBandSmooth49]),0 | Fill Color 8,8,15,200 | StrokeWidth 0
DynamicVariables=1
