[Variables]

; --------------------ContextMenu--------------------

ContextMenuSettings=Einstellungen
ContextMenuVariables=Variablen
ContextMenuRessources=Ressourcen

; --------------------Weather--------------------

WeatherDaysSub="Mon":"MO","Tue":"DI","Wed":"MI","Thu":"DO","Fri":"FR","Sat":"SA","Sun":"SO"

; --------------------Settings--------------------
; -----All-----
Title=Einstellungen
LabelGeneral=Generell
LabelDrives=Laufwerke
LabelVisualizer=Visualizer
LabelWeather=Wetter

; -----General-----
LabelMainColor=Hauptfarbe
LabelSecondColor=Zweitfarbe
LabelThirdColor=Drittfarbe
LabelTransparency=Transparenz
LabelCutout=Ausschnitt
LabelLanguage=Sprache

; -----Drives-----
LabelDriveCount=Anzahl Laufwerke
LabelDrive=Laufwerk

; -----Visualizer-----
LabelFlip=Visualizer umdrehen
LabelBarCount=Balkenanzahl
LabelBarHeight=Balkenhöhe
LabelBarWidth=Balkenbreite
LabelBarMinHeight=Balkenmindesthöhe
LabelBarGap=Balkenlücke
LabelBarRadius=Balkenradius
LabelColor=Farbe

; -----Weather-----
LabelLocation=Standort
LabelTempUnit=Temperatureinheit

; --------------------Search--------------------
; -----Google&Youtube-----
LabelAll=Alle
LabelVideos=Videos

; -----Google-----
LabelImages=Bilder
LabelShopping=Shopping

; -----Youtube-----
LabelChannels=Kanäle
LabelPlaylists=Playlists

; -----Stackoverflow-----
LabelRelevance=Relevanz
LabelNewest=Neuste

; --------------------Drive--------------------

FreeOf=frei von
