[Variables]

; --------------------ContextMenu--------------------

ContextMenuSettings=Settings
ContextMenuVariables=Variables
ContextMenuRessources=Ressources

; --------------------Weather--------------------

WeatherDaysSub="Mon":"MO","Tue":"TU","Wed":"WE","Thu":"TH","Fri":"FR","Sat":"SA","Sun":"SU"

; --------------------Settings--------------------
; -----All-----
Title=Settings
LabelGeneral=General
LabelDrives=Drives
LabelVisualizer=Visualizer
LabelWeather=Weather

; -----General-----
LabelMainColor=MainColor
LabelSecondColor=SecondColor
LabelThirdColor=ThirdColor
LabelTransparency=Transparency
LabelCutout=Cutout
LabelLanguage=Language

; -----Drives-----
LabelDriveCount=Drive Count
LabelDrive=Drive

; -----Visualizer-----
LabelFlip=Flip Visualizer
LabelBarCount=BarCount
LabelBarHeight=BarHeight
LabelBarWidth=BarWidth
LabelBarMinHeight=BarMinHeight
LabelBarGap=BarGap
LabelBarRadius=BarRadius
LabelColor=Color

; -----Weather-----
LabelLocation=Location
LabelTempUnit=Temperature Unit

; --------------------Search--------------------
; -----Google&Youtube-----
LabelAll=All
LabelVideos=Videos

; -----Google-----
LabelImages=Images
LabelShopping=Shopping

; -----Youtube-----
LabelChannels=Channels
LabelPlaylists=Playlists

; -----Stackoverflow-----
LabelRelevance=Relevance
LabelNewest=Newest

; --------------------Drive--------------------

FreeOf=free of
